### ISSUE TITLE
runipy deprecated - Duplicate, can delete

### ISSUE THREAD

**Issue by MYPei** [edbennett/publishing-analysis#9] opened 2022-03-09 11:50 UTC
Page: https://edbennett.github.io/publishing-analysis/04-jupyter/index.html

Issue: runipy is deprecated for newer versions of IPython - suggested alternative is described in  https://nbconvert.readthedocs.io/en/latest/execute_api.html

**Comment by edbennett** [comment] 2022-03-09 11:52
Closed as duplicate of #8

**Closed as completed** 2022-03-09 11:52 UTC
